/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CargaDatos;

import Ingreso.ConexionMySQL;
import Login.Sistema;
import com.itextpdf.text.DocumentException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Pedidos extends javax.swing.JFrame {
         //CONECCION CON BASE DE DATOS
    ConexionMySQL cc=new ConexionMySQL(); 
    Connection con=ConexionMySQL.GetConnection(); 
   
    public Pedidos() {
        initComponents();
        this.setLocationRelativeTo(null);
       this.txtfechaaa.setVisible(false);
       this.btnagregar.setEnabled(false);
       this.tbborrar.setEnabled(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnverpedidos = new javax.swing.JButton();
        tbborrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpedidos = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        txtidsocioo = new javax.swing.JTextField();
        txtidalquiler = new javax.swing.JTextField();
        txtfecha = new com.toedter.calendar.JDateChooser();
        txtfechaaa = new javax.swing.JTextField();
        txthora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnverpedidos.setText("VER PEDIDOS");
        btnverpedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverpedidosActionPerformed(evt);
            }
        });

        tbborrar.setText("BORRAR");
        tbborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbborrarActionPerformed(evt);
            }
        });

        tblpedidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblpedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HORA", "FECHA", "ID SOCIO", "ID ALQUILER"
            }
        ));
        tblpedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpedidos);

        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        txtidsocioo.setText("id socio");

        txtidalquiler.setText("id alquiler");

        txtfechaaa.setColumns(1);
        txtfechaaa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfechaaa.setText("txtfechaaa");
        txtfechaaa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txthora.setText("hora");

        jLabel1.setText("ID SOCIO:");

        jLabel2.setText("FECHA:");

        jLabel3.setText("HORA:");

        jLabel4.setText("ID ALQUILER:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnverpedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfechaaa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtidalquiler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addComponent(txthora, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtidsocioo, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidsocioo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfechaaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3))
                            .addComponent(txthora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidalquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnverpedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel14.setText("Clup Papel Misonero ");

        jLabel15.setText("Tel- 3743-591444");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel16.setText("jLabel3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel15))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnverpedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverpedidosActionPerformed
           try {
            Statement st = con.createStatement();
            String db="clupapel";
            String tb="pedidosocio";
            java.util.Date date = new java.util.Date();

           
            String columnas="desc"+tb;
            String sql="select * from pedidosocio";
            ResultSet rstb=st.executeQuery(sql);
            ResultSetMetaData rsmd=rstb.getMetaData();
            int col=rsmd.getColumnCount();
            DefaultTableModel modelo=new DefaultTableModel();
            this.tblpedidos.setModel(modelo);
            
            for(int i=1;i<=col;i++)
            {modelo.addColumn(rsmd.getColumnLabel(i));}
            
            while(rstb.next()){
                String fila[]=new String[col];
                for(int j=0;j<col;j++){
                    fila[j]=rstb.getString(j+1);}
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerIngresos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnverpedidosActionPerformed

    private void tbborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbborrarActionPerformed
     
        try {
            //el correo es para mandar un correo al usuario que su pedido fue rechasado
            int idusuario=Integer.parseInt(txtidsocioo.getText());
            String SQL="select * from socios where idsocio= '" +idusuario+ "' ";
            
            
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);

            if(rs.next()){
                //traigo el correo para mandarle un correo disiendo que no se reservo
                String correo=rs.getString("correo_electronico");
                
            }   } catch (SQLException ex) {                                          
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
         
      int idsocio=Integer.parseInt(txtidsocioo.getText());
      int idalquiler=Integer.parseInt(txtidalquiler.getText());
      String Ssql = "DELETE FROM ingresos WHERE idsocio='" +idsocio+ "' and idalquiler='" +idalquiler+ "'";
        
        try { 
            PreparedStatement prest = con.prepareStatement(Ssql);
            prest.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Borrado correcto");
            
        } catch (SQLException ex) {
            Logger.getLogger(VerIngresos.class.getName()).log(Level.SEVERE, null, ex);
        }
                              
        

    }//GEN-LAST:event_tbborrarActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
   
        
        try {
   
        
            
            int idusuario=Integer.parseInt(txtidsocioo.getText());
            String SQL="select * from socios where idsocio= '" +idusuario+ "' ";
            String nombre = null;    
            String direccion = null;
            String telefono=null;
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);

            if(rs.next()){
                JOptionPane.showMessageDialog(null,"ccccc");
                nombre=rs.getString("nombre");
                direccion=rs.getString("direccion");
                telefono=rs.getString("telefono");
                
                //traigo el correo para mandarle un correo disiendo que si se reservo
                //String correo=rs.getString("correo_electronico");
            }
            
          int idalquiler=Integer.parseInt(txtidalquiler.getText());
            String SQLL="select * from tipo_alquiler where idalquiler= '" +idalquiler+ "' ";
            String nombree = null;    
            
            Statement stt=con.createStatement();
            ResultSet rss=stt.executeQuery(SQLL);

            if(rss.next()){
                
                nombree=rs.getString("nombre");
               
                
                //traigo el correo para mandarle un correo disiendo que si se reservo
                //String correo=rs.getString("correo_electronico");
            }

            
            java.util.Date date = new java.util.Date();
            java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(txtfecha.getDate());
                
            int precio=0;
            
            String hora_fija="no";

            
        int horaa=Integer.parseInt(txthora.getText());
        int minuto=0;
        int segundo=0;
        
        DateFormat jj = new SimpleDateFormat("hh:mm:ss");
        Time hora = new Time(horaa,minuto,segundo);

            int borrado=0;

            
            //CARGO LOS DATOS
            PreparedStatement pps;
         
            pps = con.prepareStatement("INSERT INTO alquiler(hora,fecha,hora_fija,idsocio,precio,idalquiler,nombre,direccion,telefono,borrado)" + "VALUES (?,?,?,?,?,?,?,?,?,?)");
            pps.setTime(1,hora);
            pps.setString(2,fecha);
            pps.setString(3,hora_fija);
            pps.setInt(4,idusuario);
            pps.setInt(5,precio);
            pps.setInt(6,idalquiler);
            pps.setString(7,nombre);
            pps.setString(8, direccion);
            pps.setString(9,telefono);
            pps.setInt(10,borrado);
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserto correcto");
            
                            PlantillaAlquiler miplantilla= new PlantillaAlquiler(nombre,direccion,precio,"D:\\Universidad Analista\\programacion Patricia\\segundo parcial,final\\Club Papel\\Imagenes\\Imagenes\\Logo.png",nombree,telefono,horaa,minuto,segundo,fecha);
        try {
            miplantilla.crearPlantilla();
        } catch (DocumentException ex) {
            Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"inserto incorrecto");
        }
                    
      
      
    }//GEN-LAST:event_btnagregarActionPerformed

    private void tblpedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpedidosMouseClicked
        int seleccionar=tblpedidos.rowAtPoint(evt.getPoint());
        txthora.setText(String.valueOf(tblpedidos.getValueAt(seleccionar,0)));
        txtidalquiler.setText(String.valueOf(tblpedidos.getValueAt(seleccionar,3)));
        txtidsocioo.setText(String.valueOf(tblpedidos.getValueAt(seleccionar,2)));
        txtfechaaa.setText(String.valueOf(tblpedidos.getValueAt(seleccionar,1)));
         this.btnagregar.setEnabled(true);
       this.tbborrar.setEnabled(true);
       if (!txtfechaaa.getText().isEmpty()) {
        try {
            java.util.Date fecha = new SimpleDateFormat("yyyy-MM-dd").parse(txtfechaaa.getText());
            txtfecha.setDate(fecha);
        } catch (ParseException ex) {
            ex.printStackTrace(System.out);
            JOptionPane.showMessageDialog(this, "Formato incorrecto");
        }
    }     
    }//GEN-LAST:event_tblpedidosMouseClicked


 
   
  
 
 /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    
        /* Create and display the form */
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnverpedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tbborrar;
    private javax.swing.JTable tblpedidos;
    private com.toedter.calendar.JDateChooser txtfecha;
    private javax.swing.JTextField txtfechaaa;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txtidalquiler;
    private javax.swing.JTextField txtidsocioo;
    // End of variables declaration//GEN-END:variables
}

