/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CargaDatos;

import Ingreso.ConexionMySQL;
import Login.Sistema;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maxii
 */
public class VerAlquiler extends javax.swing.JFrame {
      //CONECCION CON BASE DE DATOS
    ConexionMySQL cc=new ConexionMySQL(); 
    Connection con=ConexionMySQL.GetConnection();

    /**
     * Creates new form VerAlquiler
     */
    public VerAlquiler() {
        initComponents();
       this.setLocationRelativeTo(null);
       this.txtfechaa.setVisible(false);
       this.txthoraa.setVisible(false);
       this.txtidalquilerr.setVisible(false);
       this.txtfechao.setVisible(false);
       
       this.txthora.setEditable(false);
       this.txthorafija.setEditable(false);
       this.txtidsocio.setEditable(false);
       this.txtprecio.setEditable(false);
       this.txtidalquiler.setEditable(false);
       this.txtnombre.setEditable(false);
       this.txtdireccion.setEditable(false);
       this.txttelefono.setEditable(false);
       this.btnmodificarr.setEnabled(false);
       this.btnaliminar.setEnabled(false);
       this.btnmodificar.setEnabled(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbxgrilla = new javax.swing.JComboBox<>();
        btnalquiler = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfechaa = new javax.swing.JTextField();
        txthora = new javax.swing.JTextField();
        txthorafija = new javax.swing.JTextField();
        txtidsocio = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtidalquiler = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        btnaliminar = new javax.swing.JButton();
        btnfecha = new javax.swing.JButton();
        txtfecha = new com.toedter.calendar.JDateChooser();
        lblfecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblventas = new javax.swing.JTable();
        txtfecho = new com.toedter.calendar.JDateChooser();
        btnmodificar = new javax.swing.JButton();
        txtidalquilerr = new javax.swing.JTextField();
        txthoraa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        txtfechao = new com.toedter.calendar.JDateChooser();
        btnmodificarr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel14.setText("Clup Papel Misonero ");

        jLabel15.setText("Tel- 3743-591444");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel16.setText("jLabel3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(212, 212, 212))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        cbxgrilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancha", "Salon", "Pileta" }));

        btnalquiler.setText("VER ALQUILERES");
        btnalquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalquilerActionPerformed(evt);
            }
        });

        jLabel2.setText("FECHA:");

        jLabel1.setText("HORA:");

        jLabel3.setText("HORA FIJA:");

        jLabel4.setText("ID SOCIO:");

        jLabel5.setText("PRECIO:");

        txtfechaa.setText("fecha");

        txthora.setText("hora");

        txthorafija.setText("hora fija");

        txtidsocio.setText("id socio");

        txtprecio.setText("precio");

        jLabel6.setText("ID ALQUILER:");

        txtidalquiler.setText("id alquiler");

        jLabel7.setText("NOMBRE:");

        jLabel8.setText("DIRECCION:");

        txtnombre.setText("nombre");

        txtdireccion.setText("direccion");

        btnaliminar.setText("ELIMINAR");
        btnaliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaliminarActionPerformed(evt);
            }
        });

        btnfecha.setText("VER ALQUILER DE ESA FECHA");
        btnfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfechaActionPerformed(evt);
            }
        });

        lblfecha.setText("INGRESE FECHA");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "HORA", "HORA FIJA", "ID SOCIO", "PRECIO", "ID ALQUILER", "NOMBRE", "DIRECCION"
            }
        ));
        tblventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblventasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblventas);

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        txtidalquilerr.setText("idalquiler");

        txthoraa.setText("hora");
        txthoraa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoraaActionPerformed(evt);
            }
        });

        jLabel9.setText("TELEFONO:");

        txttelefono.setText("telefono");
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });

        btnmodificarr.setText("GUARDAR");
        btnmodificarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnaliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnmodificar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnmodificarr))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtidalquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                                    .addComponent(txthorafija)
                                                    .addComponent(txthora)
                                                    .addComponent(txtprecio)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txttelefono)
                                                    .addComponent(txtfecho, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtidsocio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtidalquilerr, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                            .addComponent(txthoraa, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                            .addComponent(txtfechaa, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                            .addComponent(txtfechao, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnfecha)
                                        .addGap(8, 8, 8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnalquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(151, 151, 151))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbxgrilla, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(186, 186, 186)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfechao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtfechaa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addComponent(txtfecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txthoraa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txthorafija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(cbxgrilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnalquiler)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnfecha)))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtidsocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtidalquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidalquilerr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnaliminar)
                            .addComponent(btnmodificar)
                            .addComponent(btnmodificarr)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfechaActionPerformed
        try {
            String admin = (String) cbxgrilla.getSelectedItem();
            int tipo_alquiler = 0;

            
            if(admin=="Cancha"){
                tipo_alquiler=1;
            }else if(admin=="Salon"){
                tipo_alquiler=2;
            }else if(admin=="Pileta"){
                tipo_alquiler=3;
            }
            Statement st = con.createStatement();
            String db="clupapel";
            String tb="alquiler";
            java.util.Date date = new java.util.Date();
            java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(txtfecha.getDate());

            
            String columnas="desc"+tb;
            String sql="select * from alquiler where fecha='" +fecha+ "' idalquiler= '" +tipo_alquiler+ "' ";
            ResultSet rstb=st.executeQuery(sql);
            ResultSetMetaData rsmd=rstb.getMetaData();
            int col=rsmd.getColumnCount();
            DefaultTableModel modelo=new DefaultTableModel();
            this.tblventas.setModel(modelo);

            for(int i=1;i<=col;i++)
            {modelo.addColumn(rsmd.getColumnLabel(i));}

            while(rstb.next()){
                String fila[]=new String[col];
                for(int j=0;j<col;j++){
                    fila[j]=rstb.getString(j+1);}
                modelo.addRow(fila);
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerIngresos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }

        private void btngastosmesActionPerformed(java.awt.event.ActionEvent evt) {

    }//GEN-LAST:event_btnfechaActionPerformed

    private void btnalquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalquilerActionPerformed
        try {
            String admin = (String) cbxgrilla.getSelectedItem();
            int tipo_alquiler = 0;

            if(admin=="Cancha"){
                tipo_alquiler=1;
            }else if(admin=="Salon"){
                tipo_alquiler=2;
            }else if(admin=="Pileta"){
                tipo_alquiler=3;
            }
            Statement st = con.createStatement();
            String db="clupapel";
            String tb="alquiler";
            int borrar=0;
            String columnas="desc"+tb;
            String sql="select * from alquiler where idalquiler= '" +tipo_alquiler+ "' and borrado='" +borrar+ "' ";
            ResultSet rstb=st.executeQuery(sql);
            ResultSetMetaData rsmd=rstb.getMetaData();
            int col=rsmd.getColumnCount();
            DefaultTableModel modelo=new DefaultTableModel();
            this.tblventas.setModel(modelo);

            for(int i=1;i<=col;i++)
            {modelo.addColumn(rsmd.getColumnLabel(i));}

            while(rstb.next()){
                String fila[]=new String[col];
                for(int j=0;j<col;j++){
                    fila[j]=rstb.getString(j+1);}
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerIngresos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnalquilerActionPerformed

    private void tblventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblventasMouseClicked
        int seleccionar=tblventas.rowAtPoint(evt.getPoint());
        txthora.setText(String.valueOf(tblventas.getValueAt(seleccionar,0)));
        txthoraa.setText(String.valueOf(tblventas.getValueAt(seleccionar,0)));
        txtnombre.setText(String.valueOf(tblventas.getValueAt(seleccionar,6)));
        txtfechaa.setText(String.valueOf(tblventas.getValueAt(seleccionar,1)));
        txtprecio.setText(String.valueOf(tblventas.getValueAt(seleccionar,4)));
        txtdireccion.setText(String.valueOf(tblventas.getValueAt(seleccionar,7)));
        txttelefono.setText(String.valueOf(tblventas.getValueAt(seleccionar,8)));
        txtidalquiler.setText(String.valueOf(tblventas.getValueAt(seleccionar,5)));
        txtidalquilerr.setText(String.valueOf(tblventas.getValueAt(seleccionar,5)));
        txtidsocio.setText(String.valueOf(tblventas.getValueAt(seleccionar,3)));
        txthorafija.setText(String.valueOf(tblventas.getValueAt(seleccionar,2)));
         this.btnaliminar.setEnabled(true);
         this.btnmodificar.setEnabled(true);
        
           if (!txtfechaa.getText().isEmpty()) {
        try {
            java.util.Date fecha = new SimpleDateFormat("yyyy-MM-dd").parse(txtfechaa.getText());
            txtfecho.setDate(fecha);
            txtfechao.setDate(fecha);
        } catch (ParseException ex) {
            ex.printStackTrace(System.out);
            JOptionPane.showMessageDialog(this, "Formato incorrecto");
        }
        
        
    }//GEN-LAST:event_tblventasMouseClicked
    }
    private void btnaliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaliminarActionPerformed
      java.util.Date date = new java.util.Date();
            java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(txtfecho.getDate());
    int borrar=1;

      String Ssql = "UPDATE alquiler SET borrado='" +borrar+ "' WHERE fecha='" +fecha+ "'";
        
        try { 
            PreparedStatement prest = con.prepareStatement(Ssql);
            prest.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Modificacion correcta");
            
        } catch (SQLException ex) {
            Logger.getLogger(VerIngresos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Modificacion incorrecta");
        }
    }//GEN-LAST:event_btnaliminarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
       this.txtfechaa.setVisible(true);
       this.txthora.setEditable(true);
       this.txthorafija.setEditable(true);
       this.txtidsocio.setEditable(true);
       this.txtprecio.setEditable(true);
       this.txtidalquiler.setEditable(true);
       this.txtnombre.setEditable(true);
       this.txtdireccion.setEditable(true);
       this.txttelefono.setEditable(true);
       this.btnmodificarr.setEnabled(true);
       this.btnaliminar.setEnabled(false);
       this.txthora.setText("");
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void txthoraaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoraaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoraaActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void btnmodificarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarrActionPerformed
              java.util.Date date = new java.util.Date();
            java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(txtfecho.getDate());
         //VARIABLE HORA
        int horaa=Integer.parseInt(txthora.getText());
        int minuto=0;
        int segundo=0;
        DateFormat jjj = new SimpleDateFormat("hh:mm:ss");
        Time hora = new Time(horaa,minuto,segundo);
    int precio=Integer.parseInt(txtprecio.getText());
    int idalquiler=Integer.parseInt(txtidalquiler.getText());
    int idsocio=Integer.parseInt(txtidsocio.getText());
    String hora_fija=String.valueOf(txthorafija.getText());
    String nombre=String.valueOf(txtnombre.getText());
    String direccion=String.valueOf(txtdireccion.getText());
    String telefono=String.valueOf(txttelefono.getText());

      String Ssql = "UPDATE alquiler SET hora='" +hora+ "' WHERE fecha='" +fecha+ "'";
        String Ssqll = "UPDATE alquiler SET precio='" +precio+ "'  WHERE fecha='" +fecha+ "'";
        String Ssqlll = "UPDATE alquiler SET idalquiler='" +idalquiler+ "'  WHERE fecha='" +fecha+ "'";
        String Ssqllll = "UPDATE alquiler SET hora_fija='" +hora_fija+ "'  WHERE fecha='" +fecha+ "'";
        String Ssqllo = "UPDATE alquiler SET idsocio='" +idsocio+ "'  WHERE fecha='" +fecha+ "'";
        String Ssqlloo = "UPDATE alquiler SET nombre='" +nombre+ "'  WHERE fecha='" +fecha+ "'";
        String Ssqllol = "UPDATE alquiler SET direccion='" +direccion+ "'  WHERE fecha='" +fecha+ "'";
        String Ssqllooo = "UPDATE alquiler SET fecha='" +fecha+ "'  WHERE fecha='" +fecha+ "'";
        String Ssqlllll = "UPDATE alquiler SET telefono='" +telefono+ "'  WHERE fecha='" +fecha+ "'";
        
        try { 
            PreparedStatement prest = con.prepareStatement(Ssql);
            prest.executeUpdate();
            PreparedStatement presto = con.prepareStatement(Ssqll);
            presto.executeUpdate();
              PreparedStatement prestoo = con.prepareStatement(Ssqlll);
            prestoo.executeUpdate();
              PreparedStatement prestooo = con.prepareStatement(Ssqllll);
            prestooo.executeUpdate();
              PreparedStatement prestoooo = con.prepareStatement(Ssqllo);
            prestoooo.executeUpdate();
              PreparedStatement prestooooo = con.prepareStatement(Ssqlloo);
            prestooooo.executeUpdate();
              PreparedStatement prestoooooo = con.prepareStatement(Ssqllol);
            prestoooooo.executeUpdate();
              PreparedStatement prestooooooo = con.prepareStatement(Ssqllooo);
            prestooooooo.executeUpdate();
            PreparedStatement prestoooooooo = con.prepareStatement(Ssqlllll);
            prestoooooooo.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Modificacion correcta");
            
        } catch (SQLException ex) {
            Logger.getLogger(VerIngresos.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null,"Modificacion incorrecta");
        }
    }//GEN-LAST:event_btnmodificarrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerAlquiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaliminar;
    private javax.swing.JButton btnalquiler;
    private javax.swing.JButton btnfecha;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnmodificarr;
    private javax.swing.JComboBox<String> cbxgrilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JTable tblventas;
    private javax.swing.JTextField txtdireccion;
    private com.toedter.calendar.JDateChooser txtfecha;
    private javax.swing.JTextField txtfechaa;
    private com.toedter.calendar.JDateChooser txtfechao;
    private com.toedter.calendar.JDateChooser txtfecho;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txthoraa;
    private javax.swing.JTextField txthorafija;
    private javax.swing.JTextField txtidalquiler;
    private javax.swing.JTextField txtidalquilerr;
    private javax.swing.JTextField txtidsocio;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
